### ISSUE TITLE
Problem in Windows

### ISSUE THREAD

**Issue by MillerSilva** [mgubi/tm-julia#1]
Hello, I tried to install the plugin as follows, I pasted the folder inside the / TeXmacs / plugins folder then I closed and opened the program, but it does not recognize it. I use Windows.

**Comment by mgubi** [comment]
Maybe verify that the name of the folder has to be 'julia' and not 'tm-julia' (which is the name of the repo' check the README.md.

**Comment by mgubi** [comment]
Seems ok. Maybe you can check if julia is visible from TeXmacs. Open a Scheme session in TeXmacs and then run the command
```
(url-exists-in-path? "julia")
```
if returns #f then there is a problem and TeXmacs cannot find Julia. Otherwise it should return #t.

**Comment by mgubi** [comment]
If you know where Julia is installed and which path to look for, I can modify the file prog/init-julia.scm to take this into account.

**Comment by mgubi** [comment]
This has been fixed now in the repository. Thanks to @jeroen for finding the problem.
