### ISSUE TITLE
one character is chopped off of `print`ed strings

### ISSUE THREAD

**Issue by woutersj** [mgubi/tm-julia#7]
When using `print` to output a string, the last character is chopped off of the output.

`print` outputs to `stdout` and does not generate a `result` when evaulated in `string_include`. The output goes straight to TMJuliaStdio, which chops off a character in line 128 of TeXmacsJulia.jl. Removing `chop` in that line seems to solve the problem, seemingly without negative side effects.

**Comment by mgubi** [comment]
Ok, i implement this change. I do not remember the reason for that chop. What to do for stderr?

**Comment by mgubi** [comment]
Fixed in 219a278
